"""add agents, keylogs and metrics

Revision ID: 03722a03c7c3
Revises: 
Create Date: 2026-03-20 19:33:48.659009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03722a03c7c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('os_release', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('processor', sa.String(), nullable=True),
    sa.Column('physical_cores', sa.Integer(), nullable=True),
    sa.Column('total_cores', sa.Integer(), nullable=True),
    sa.Column('max_frequency', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keylogs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('app', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keylogs_agent_id'), 'keylogs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_keylogs_app'), 'keylogs', ['app'], unique=False)
    op.create_index(op.f('ix_keylogs_timestamp'), 'keylogs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_keylogs_type'), 'keylogs', ['type'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_used_percent', sa.Float(), nullable=True),
    sa.Column('memory_total_gb', sa.Float(), nullable=True),
    sa.Column('memory_available_gb', sa.Float(), nullable=True),
    sa.Column('disk_used_percent', sa.Float(), nullable=True),
    sa.Column('disk_total_gb', sa.Float(), nullable=True),
    sa.Column('bytes_sent_total', sa.Float(), nullable=True),
    sa.Column('bytes_recv_total', sa.Float(), nullable=True),
    sa.Column('packets_sent_total', sa.Float(), nullable=True),
    sa.Column('packets_recv_total', sa.Float(), nullable=True),
    sa.Column('upload_speed_kb', sa.Float(), nullable=True),
    sa.Column('download_speed_kb', sa.Float(), nullable=True),
    sa.Column('uptime_hours', sa.Float(), nullable=True),
    sa.Column('process_count', sa.Integer(), nullable=True),
    sa.Column('battery_percent', sa.Float(), nullable=True),
    sa.Column('battery_plugged', sa.String(), nullable=True),
    sa.Column('current_app', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_agent_id'), 'metrics', ['agent_id'], unique=False)
    op.create_index(op.f('ix_metrics_timestamp'), 'metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_timestamp'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_agent_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_keylogs_type'), table_name='keylogs')
    op.drop_index(op.f('ix_keylogs_timestamp'), table_name='keylogs')
    op.drop_index(op.f('ix_keylogs_app'), table_name='keylogs')
    op.drop_index(op.f('ix_keylogs_agent_id'), table_name='keylogs')
    op.drop_table('keylogs')
    op.drop_table('agents')
    # ### end Alembic commands ###
