"""add screenshots

Revision ID: 6b4674c5c290
Revises: b6996d71ec41
Create Date: 2026-03-25 15:00:10.865626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4674c5c290'
down_revision: Union[str, None] = 'b6996d71ec41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenshots_agent_id'), 'screenshots', ['agent_id'], unique=False)
    op.create_index(op.f('ix_screenshots_created_at'), 'screenshots', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screenshots_created_at'), table_name='screenshots')
    op.drop_index(op.f('ix_screenshots_agent_id'), table_name='screenshots')
    op.drop_table('screenshots')
    # ### end Alembic commands ###
