"""add clipboards

Revision ID: b6996d71ec41
Revises: 03722a03c7c3
Create Date: 2026-03-23 15:24:57.029170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6996d71ec41'
down_revision: Union[str, None] = '03722a03c7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clipboards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('app', sa.String(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clipboards_agent_id'), 'clipboards', ['agent_id'], unique=False)
    op.create_index(op.f('ix_clipboards_app'), 'clipboards', ['app'], unique=False)
    op.create_index(op.f('ix_clipboards_timestamp'), 'clipboards', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clipboards_timestamp'), table_name='clipboards')
    op.drop_index(op.f('ix_clipboards_app'), table_name='clipboards')
    op.drop_index(op.f('ix_clipboards_agent_id'), table_name='clipboards')
    op.drop_table('clipboards')
    # ### end Alembic commands ###
